name: Build Randy OS Installer
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x workflows/build.sh

      - name: Run Build Script
        run: ./workflows/build.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Randy-USB-Installer
          path: |
            randy-installer-env/randy-os-intel.tar
            randy-installer-env/localhost.apkovl.tar.gz