name: Build Randy OS Installer
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x build-void.sh

      - name: Run Build Script
        run: ./build-void.sh

      - name: Inject Payload into Etcher-Ready ISO
        run: |
          echo "Installing xorriso..."
          sudo apt-get update
          sudo apt-get install -y xorriso
          
          echo "Downloading base Alpine Linux ISO..."
          wget -q https://dl-cdn.alpinelinux.org/alpine/v3.19/releases/x86_64/alpine-standard-3.19.1-x86_64.iso
          
          echo "Baking custom files into the ISO..."
          xorriso -indev alpine-standard-3.19.1-x86_64.iso \
                  -outdev randy-installer.iso \
                  -map randy-installer-env/randy-os-intel.tar /randy-os-intel.tar \
                  -map randy-installer-env/localhost.apkovl.tar.gz /localhost.apkovl.tar.gz \
                  -boot_image any replay

      - name: Upload Etcher-Ready Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Randy-USB-Installer-ISO
          path: randy-installer.iso